### ISSUE TITLE
Failed file reads

### ISSUE THREAD

**Issue by jarroy** [metno/NWPdocs#1]
I try to read data, one day at the time, and I get the following issues. I do not know which of 24 files in each file that ails
Day:  0
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/10/17/met_analysis_1_0km_nordic_20171017T00Z.nc
Day:  1
**http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/10/18/met_analysis_1_0km_nordic_20171018T00Z.nc
Read failed:  'air_pressure_at_sea_level' <class 'KeyError'>**
Day:  2
**http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/10/19/met_analysis_1_0km_nordic_20171019T00Z.nc
Read failed:  NetCDF: Not a valid ID <class 'RuntimeError'>**
etc.
Day:  1
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/03/01/met_analysis_1_0km_nordic_20190301T00Z.nc
Read failed:  'time' <class 'KeyError'>

Does anyone know where these errors come from? The "Not a Valid ID" message seems to coma and go unpredictable.

Trying to read all dates in the period 20161127 up to but not including 20190501 gives this list of errors:
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/02/03/met_analysis_1_0km_nordic_20170203T00Z.nc
Read failed:  master dataset http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/04/06/met_analysis_1_0km_nordic_20170406T00Z.nc does not have any variables to aggregate
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/04/06/met_analysis_1_0km_nordic_20170406T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/08/16/met_analysis_1_0km_nordic_20170816T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/08/17/met_analysis_1_0km_nordic_20170817T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/08/18/met_analysis_1_0km_nordic_20170818T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/09/17/met_analysis_1_0km_nordic_20170917T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/09/18/met_analysis_1_0km_nordic_20170918T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/09/25/met_analysis_1_0km_nordic_20170925T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/10/18/met_analysis_1_0km_nordic_20171018T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/10/19/met_analysis_1_0km_nordic_20171019T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/10/20/met_analysis_1_0km_nordic_20171020T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/10/21/met_analysis_1_0km_nordic_20171021T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/11/07/met_analysis_1_0km_nordic_20171107T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/11/08/met_analysis_1_0km_nordic_20171108T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/11/14/met_analysis_1_0km_nordic_20171114T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/12/25/met_analysis_1_0km_nordic_20171225T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/12/26/met_analysis_1_0km_nordic_20171226T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2017/12/31/met_analysis_1_0km_nordic_20171231T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/01/13/met_analysis_1_0km_nordic_20180113T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/01/16/met_analysis_1_0km_nordic_20180116T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/01/17/met_analysis_1_0km_nordic_20180117T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/01/25/met_analysis_1_0km_nordic_20180125T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/02/27/met_analysis_1_0km_nordic_20180227T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/02/28/met_analysis_1_0km_nordic_20180228T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/03/01/met_analysis_1_0km_nordic_20180301T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/03/02/met_analysis_1_0km_nordic_20180302T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/03/04/met_analysis_1_0km_nordic_20180304T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/03/05/met_analysis_1_0km_nordic_20180305T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/03/09/met_analysis_1_0km_nordic_20180309T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/03/12/met_analysis_1_0km_nordic_20180312T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/03/18/met_analysis_1_0km_nordic_20180318T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/03/22/met_analysis_1_0km_nordic_20180322T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/05/30/met_analysis_1_0km_nordic_20180530T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/06/01/met_analysis_1_0km_nordic_20180601T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/06/25/met_analysis_1_0km_nordic_20180625T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/06/28/met_analysis_1_0km_nordic_20180628T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/07/09/met_analysis_1_0km_nordic_20180709T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/07/10/met_analysis_1_0km_nordic_20180710T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/07/13/met_analysis_1_0km_nordic_20180713T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/07/14/met_analysis_1_0km_nordic_20180714T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/07/15/met_analysis_1_0km_nordic_20180715T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/07/16/met_analysis_1_0km_nordic_20180716T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/07/17/met_analysis_1_0km_nordic_20180717T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/07/23/met_analysis_1_0km_nordic_20180723T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/09/08/met_analysis_1_0km_nordic_20180908T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/09/26/met_analysis_1_0km_nordic_20180926T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/09/27/met_analysis_1_0km_nordic_20180927T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/10/02/met_analysis_1_0km_nordic_20181002T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/10/10/met_analysis_1_0km_nordic_20181010T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/10/11/met_analysis_1_0km_nordic_20181011T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/10/15/met_analysis_1_0km_nordic_20181015T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/10/16/met_analysis_1_0km_nordic_20181016T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/10/17/met_analysis_1_0km_nordic_20181017T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/10/18/met_analysis_1_0km_nordic_20181018T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/10/28/met_analysis_1_0km_nordic_20181028T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/02/met_analysis_1_0km_nordic_20181102T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/03/met_analysis_1_0km_nordic_20181103T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/08/met_analysis_1_0km_nordic_20181108T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/09/met_analysis_1_0km_nordic_20181109T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/10/met_analysis_1_0km_nordic_20181110T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/12/met_analysis_1_0km_nordic_20181112T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/13/met_analysis_1_0km_nordic_20181113T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/14/met_analysis_1_0km_nordic_20181114T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/15/met_analysis_1_0km_nordic_20181115T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/19/met_analysis_1_0km_nordic_20181119T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/20/met_analysis_1_0km_nordic_20181120T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/21/met_analysis_1_0km_nordic_20181121T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/22/met_analysis_1_0km_nordic_20181122T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/23/met_analysis_1_0km_nordic_20181123T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/24/met_analysis_1_0km_nordic_20181124T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/11/27/met_analysis_1_0km_nordic_20181127T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/04/met_analysis_1_0km_nordic_20181204T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/05/met_analysis_1_0km_nordic_20181205T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/07/met_analysis_1_0km_nordic_20181207T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/08/met_analysis_1_0km_nordic_20181208T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/09/met_analysis_1_0km_nordic_20181209T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/10/met_analysis_1_0km_nordic_20181210T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/11/met_analysis_1_0km_nordic_20181211T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/12/met_analysis_1_0km_nordic_20181212T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/13/met_analysis_1_0km_nordic_20181213T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/23/met_analysis_1_0km_nordic_20181223T00Z.nc
Read failed:  'air_pressure_at_sea_level'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/24/met_analysis_1_0km_nordic_20181224T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/25/met_analysis_1_0km_nordic_20181225T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2018/12/26/met_analysis_1_0km_nordic_20181226T00Z.nc
Read failed:  [Errno -70] NetCDF: DAP server error: b'http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/01/05/met_analysis_1_0km_nordic_20190105T02Z.nc'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/01/05/met_analysis_1_0km_nordic_20190105T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/01/09/met_analysis_1_0km_nordic_20190109T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/01/13/met_analysis_1_0km_nordic_20190113T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/01/16/met_analysis_1_0km_nordic_20190116T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/01/24/met_analysis_1_0km_nordic_20190124T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/01/26/met_analysis_1_0km_nordic_20190126T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/01/31/met_analysis_1_0km_nordic_20190131T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/06/met_analysis_1_0km_nordic_20190206T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/08/met_analysis_1_0km_nordic_20190208T00Z.nc
Read failed:  master dataset http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/12/met_analysis_1_0km_nordic_20190212T00Z.nc does not have a aggregation dimension
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/12/met_analysis_1_0km_nordic_20190212T00Z.nc
Read failed:  master dataset http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/14/met_analysis_1_0km_nordic_20190214T00Z.nc does not have a aggregation dimension
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/14/met_analysis_1_0km_nordic_20190214T00Z.nc
Read failed:  master dataset http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/16/met_analysis_1_0km_nordic_20190216T00Z.nc does not have a aggregation dimension
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/16/met_analysis_1_0km_nordic_20190216T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/23/met_analysis_1_0km_nordic_20190223T00Z.nc/home/jarroy/.local/lib/python3.7/site-packages/numpy/core/_methods.py:36: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial)

Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/02/26/met_analysis_1_0km_nordic_20190226T00Z.nc
Read failed:  'time'
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/03/01/met_analysis_1_0km_nordic_20190301T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/03/13/met_analysis_1_0km_nordic_20190313T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/04/03/met_analysis_1_0km_nordic_20190403T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/04/06/met_analysis_1_0km_nordic_20190406T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/04/20/met_analysis_1_0km_nordic_20190420T00Z.nc
Read failed:  NetCDF: Not a valid ID
http://thredds.met.no/thredds/dodsC/metpparchivev1/2019/04/26/met_analysis_1_0km_nordic_20190426T00Z.nc

**Comment by cristianlussana** [comment]
Here you find recommendations on how to read data from thredds
https://drive.google.com/file/d/1Mmt_l88x74wXbui1lgCVEI56egtLcW01/view
