### ISSUE TITLE
Missing files in operational 

### ISSUE THREAD

**Issue by paapu88** [metno/NWPdocs#13]
Dear All,
Are there many files missing in the archive of operational forecasts,
could not find at least these:

https://thredds.met.no/thredds/dodsC/metpparchive/2018/03/07/met_forecast_1_0km_nordic_20180307T15Z.nc
https://thredds.met.no/thredds/dodsC/metpparchive/2018/03/09/met_forecast_1_0km_nordic_20180309T16Z.nc

Terveisin, Markus

**Comment by cristianlussana** [comment]
Dear Markus,
thanks for your feedback. Yes, there might be missing files in the operational archive.
Have you considered using the re-runs for filling up the holes in your data?
You may check here:
https://thredds.met.no/thredds/catalog/metpparchivev2/catalog.html
Best regards, Cristian
