### ISSUE TITLE
3d data for Finland is rather sparse...

### ISSUE THREAD

**Issue by paapu88** [metno/NWPdocs#17]
Hei,
I'd like to get 3d data for Finland. Tried from "https://thredds.met.no/thredds/dodsC/mepslatest/meps_det_vc_2_5km_latest.nc"
In principle this data is good, but lat lon grid is pretty sparse in Finland (about 100km from one point to another...).

Is there any 3d data from metno that would be usable in Finland?
Or could you point out where in (Finland?) to get this data for free?
![newplot (2)](https://user-images.githubusercontent.com/6195764/191677628-0dc977f4-1072-49b5-8237-e10afcae91ed.png)

terveisin, Markus

**Comment by eivindsMET** [comment]
Hi Markus, 
These files are on a specific non-gridded format for selected vertical profiles and cross sections. It is used mainly by forecasters in Norway, so coverage in Finland is not that good for these files unfortunately. 
We do however have the full 4D fields available for the entire domain which covers entire Scandinavia for many parameters. Please consult the file overview here
https://github.com/metno/NWPdocs/wiki/MEPS-dataset#meps-file-overview 
where you find pointers to the files you should look for.

**Comment by paapu88** [comment]
Thanks, could you point me out any data from metno that has 3d(or 4d with time) data with decent grid from Finland?
Especially with 3d cloud and temperature information.

I may get this also from Finland, data should be there...

**Comment by eivindsMET** [comment]
I urge you to read up on the documentation. Start here https://github.com/metno/NWPdocs/wiki where you will be guided to what dataset is relevant for you, what model it is incl resolution, and then towards the files themselves. There is also guidance how to extract data. We have all the data available, openly accessible via https://thredds.met.no/thredds/metno.html

(By the way, today is system maintenance so some products are not available today. Keep updated on https://status.met.no/ for any issues in the production)

All the best,
Eivind

**Comment by paapu88** [comment]
Well, was hoping to get an answer which I did not find in your documentation.

**Comment by eivindsMET** [comment]
Well, you can start looking at MEPS det-files archive, i.e. here
https://thredds.met.no/thredds/dodsC/meps25epsarchive/2022/09/21/meps_det_2_5km_20220921T00Z.nc.html 
This is data for the entier model grid, 2.5km grid spacing. Here are parameters on pressure levels, and also model levels. You will find many different parameters, e.g. air_temperature_pl which is air temperature on pressure levels, mass_fraction_of_cloud_condensed_water_in_air_ml which is Atmospheric cloud condensed water content in model levels , and manymany other parameters as well.  There is much to digest, and the information is there. Good luck.

**Comment by paapu88** [comment]
excellent! Tusen tack!

**Comment by paapu88** [comment]
Thanks once more, the file I was looking for was in the archive directory, thats why I did not find it earlier:
opendap_url = (
    "https://thredds.met.no/thredds/dodsC/mepslatest/archive/meps_det_2_5km_latest.nc"
)

**Comment by eivindsMET** [comment]
yup. That can be confusing. Take a look on 
https://github.com/metno/NWPdocs/wiki/Data-access#accessingfiles 
:)
