### ISSUE TITLE
ground height information (oreography) for 2.5 km MEPS grid

### ISSUE THREAD

**Issue by paapu88** [metno/NWPdocs#24]
Dear Developers,

Could not find oreography info in MEPS dataset nc files (info that near Galdhøpiggen it data should show about 2400m).
Is this information available somewhere in the same 2.5km MEPS grid?

Terveisin, Markus

**Comment by paapu88** [comment]
Ok, interpolated from metno1km grid and it seems to be plausible.
![image](https://github.com/metno/NWPdocs/assets/6195764/996c5bf2-c4bd-4e9f-b543-7ba727fa22e0)

**Comment by tnipen** [comment]
Dear Markus

In the MEPS files, you can use the "surface_geopotential" field and divide by 9.81. This will give you the height the model thinks the ground is at, which can be important if you are trying to apply an elevation correction to the MEPS data towards your own set of points. But if you are just looking for a elevation field for general use, then the 1km MET Nordic field is better.

Thomas
