### ISSUE TITLE
MEPS deterministic files from 2023-12-05 00:00 to 2024-03-05 21:00 are missing

### ISSUE THREAD

**Issue by carlos-rpg** [metno/NWPdocs#26]
Hello metno,

I have noticed that the MEPS deterministic files from `meps_det_2_5km_20231205T00Z.nc` to `meps_det_2_5km_20240305T21Z.nc` are missing from https://thredds.met.no/thredds/catalog/meps25epsarchive/catalog.html.

Is it possible to know the reason of the recall and when they will be available again? Many thanks in advance.

**Comment by eivindsMET** [comment]
Hello, 
We changed our archiving policy in 2023, so these files will no longer be kept long term. Please adapt to use the corresponding ncml files instead. More details here: https://github.com/metno/NWPdocs/wiki/New-MEPS-Archive-2023 

Regards,
Eivind
