### ISSUE TITLE
Radiation data in Post Processed Analysis Product

### ISSUE THREAD

**Issue by yisak** [metno/NWPdocs#4]
There seems to be many outliers in the radiation variable for the analysis products (http://thredds.met.no/thredds/catalog/metpparchivev1/catalog.html) . Here I made the assumption that the radiation variable represents deaccumulated values and that they represent deaccumulated values over a period of 1 hour. So I just divided the values by 3600s to get W/m^2. But I see that some values are too high. Look at the plots below. I just took one point inside one of Statkrafts catchments and plotted the radiation for the whole period (2013.09.01-2018.09.01). I have also included a plot where only the values from one of the years with the outliers are plotted.
@tnipen , @cristianlussana do you know the cause for this?

![radiation_data-whole_period](https://user-images.githubusercontent.com/14080306/69638923-eea3c500-105b-11ea-9ec0-490502880916.png)

![radiation_data-one_year](https://user-images.githubusercontent.com/14080306/69638949-f95e5a00-105b-11ea-9fa0-7ca9b5c0fa3e.png)

**Comment by tnipen** [comment]
Thanks for the feedback. This has been fixed now.

![radiation](https://user-images.githubusercontent.com/1328637/69805719-8b439f80-11e1-11ea-8b8c-35fb344e57d5.png)
