### ISSUE TITLE
Wrong metadata for radiation data in post-processed forecast product

### ISSUE THREAD

**Issue by yisak** [metno/NWPdocs#5]
Some of the files in the post-processed forecast dataset ([http://thredds.met.no/thredds/catalog/metpparchivev1/catalog.html](url)) have unit for the radiation which does not match with the magnitude of the values in this variable. In the example below the unit in the metadata is W m^-2 while the variable seem to represent aggregated (integral) values. @tnipen, @cristianlussana, @ivarsei can this be fixed?
```python
f="met_forecast_1_0km_nordic_20140701T06Z.nc"
ds=nc.Dataset(f,'r')
rad = ds.variables['integral_of_surface_downwelling_shortwave_flux_in_air_wrt_time']
rad
Out[32]:
<class 'netCDF4._netCDF4.Variable'>
float32 integral_of_surface_downwelling_shortwave_flux_in_air_wrt_time(time, y, x)
    coordinates: longitude latitude
    units: W/m^2
    standard_name: surface_downwelling_shortwave_flux_in_air
    grid_mapping: projection_lcc
unlimited dimensions: time
current shape = (61, 1544, 1270)
filling on, default _FillValue of 9.969209968386869e+36 used
rad[:,:,0].max()
Out[33]: 75324344.0
```

**Comment by johtoblan** [comment]
@ivarsei 
https://thredds.met.no/thredds/dodsC/metpparchivev1/2014/07/01/met_forecast_1_0km_nordic_20140701T06Z.nc.html.

Metadata still says W/m^2

**Comment by tnipen** [comment]
This has now been fixed
