### ISSUE TITLE
Missing data in Rerun version 2

### ISSUE THREAD

**Issue by kristss** [metno/NWPdocs#7]
I've found some periods with missing data in the latest rerun. 

For 2019 there is one period of 30 hours missing from thredds:
- 2019-03-02T21Z to 2019-03-04T02Z

For 2020 the files that I could not read are:
- 2020-01-13T18Z to 2020-01-14T23Z
- 2020-01-27T19Z to 2020-01-31T23Z
- 2020-02-04T03Z to 2020-02-05T02Z
- 2020-07-07T14Z to 2020-07-07T23Z
- 2020-07-11T03Z to 2020-07-14T23Z

**Comment by cristianlussana** [comment]
Thanks for the feedback. For the moment, we have no plan to fill in the holes. However, I believe that by merging the operational archive and the rerun version 2 archive it would be possible to fill the holes.
