### ISSUE TITLE
Parameters MET Nordic

### ISSUE THREAD

**Issue by kristss** [metno/NWPdocs#8]
Are the parameters cloud_area_fraction and integral_of_surface_downwelling_shortwave_flux_in_air just the nearest neighbour of the raw model output at 2.5 km resolution? Or is there some post-processing or downscaling applied to the analysis and forecast products like nearest neighbourhood area selection? In the pdf about MEPS linked to on the [MEPS AROME Arctic](https://github.com/metno/NWPdocs/wiki/MEPS-AROME-Arctic) wiki page, it is written that post-processed cloud area fractions are the median value of a neighbourhood area of 37.5x37.5 km, but I notice that the information is a few years old and applied to the old _pp_ products.

**Comment by cristianlussana** [comment]
MET Nordic post-processing for the parameters cloud_area_fraction and integral_of_surface_downwelling_shortwave_flux_in_air are derived through a post-processing of the 2.5 km raw model output. I am not the author of the procedure but it should be a nearest neighbour (or similar). MEPS Arome Arctic is a different story and it is not related to MET Nordic methods.
