### ISSUE TITLE
wind direction/speed vs x_wind/y_wind

### ISSUE THREAD

**Issue by itshaawk** [metno/NWPdocs#9]
Some files (e.g. https://thredds.met.no/thredds/catalog/metpparchive/2019/03/04/catalog.html?dataset=metpparchive/2019/03/04/met_analysis_1_0km_nordic_20190304T10Z.nc) have x_wind/y_wind variables, while others have wind_speed/wind_direction

"wind_direction_10m.standard_name" states "wind_from_direction"

is x_wind/y_wind intended as the "wind_from_direction" as well?

**Comment by tnipen** [comment]
Hi

Yes, older files in that catalogue have x_wind and y_wind, whereas newer files provide wind_direction and wind_speed. If you need wind_direction and wind_speed back in time, use data in the "Rerun Version 2" catalogue. These are consistent with what is produced operationally today.
